Repository FreeRDP/Remmina, pull requests merged in 2018-05, with the labels that each got.

#1594 Clang LLVM coverage flags
  CMakeLists.txt
Labels: review

#1595 SPICE: add support for ssh tunnelling
  plugins/spice/spice_plugin.c
  remmina/src/remmina_ssh.c
Labels: review

#1597 RDP: option to disable fast-path, fixes #1596
  plugins/rdp/rdp_plugin.c
Labels: enhancement, review

#1624 Updated German Translation
  po/de.po
Labels: translations

#1637 Rename UNIQUE_APPNAME to REMMINA_APP_ID and use it wherever possible
  CMakeLists.txt
  config.h.in
  data/desktop/CMakeLists.txt
  src/remmina.c
  src/remmina_file.c
  src/remmina_icon.c
Labels: enhancement

#1649 Move search bar below the header.
  data/ui/remmina_main.glade
Labels: enhancement

#1650 Fixing segmentation fault due to setting name NULL
  plugins/vnc/vnc_plugin.c
  src/remmina_file.c
Labels: bug

#1653 Add search toggle
  data/ui/remmina_main.glade
  src/remmina_main.c
  src/remmina_main.h
Labels: enhancement
